app/views.py
from flask import Blueprint, render_template, request, redirect, url_for 
from .models import *
from .utils import * 
from datetime import datetime
import os 

view_blueprint =Blueprint('views', __name__)
color = os.environ.get('color', default='#910A0A')

@view_blueprint.context_processor
def inject_globals():
    print('hi')
    return make_variables(color)

@view_blueprint.get('/')
def get_home(): 
    users = User.query.all()
    tasks = Task.query.all()
    activas = len([task for task in tasks if task.complete == False])
    projects = Project.query.all()
    return render_template('home.html', users = users, tasks = tasks, projects = projects, activas = activas)

@view_blueprint.get('/create_user')
def get_create_user():
    users = User.query.all()
    tasks = Task.query.all()
    projects = Project.query.all()
    return render_template('create_user.html', users = users, tasks = tasks, projects = projects)


@view_blueprint.post('/create_user')
def post_create_user():
    user = request.form['username']
    create_user(user)
    return redirect(url_for('views.get_home'))

@view_blueprint.post('/edit_user')
def post_edit_user():
    user_id = request.form['user']
    username = request.form['username']
    edit_user(user_id, username)
    return redirect(url_for('views.get_home'))

@view_blueprint.post('/simple_delete_user')
def post_simple_delete_user():
    user_id = request.form['user']
    simple_delete(user_id)
    return redirect(url_for('views.get_home'))

@view_blueprint.post('/migrate_delete_user')
def post_migrate_delete_user():
    user_id = request.form['user']
    migrate_id = request.form['migrate']
    if user_id == migrate_id:
        return redirect(url_for('views.get_home'))
    else:
        migrate_delete(user_id, migrate_id)
        return redirect(url_for('views.get_home'))

@view_blueprint.post('/create_task')
def post_create_task():
    try:
        content = request.form['content']
        duedate = datetime.strptime(request.form['duedate'], date_format)
        project = int(request.form['project'])
        task_id = create_task(content, duedate, project)
        user_id = int(request.form['user'])
        assign_task(user_id, task_id)
        return redirect(find_redirect(request.form['type'], request.form['id']))
    except:
        return redirect(find_redirect(request.form['type'], request.form['id']))

@view_blueprint.post('/assign_task')
def post_assign_task():
    user_id = request.form['user']
    task_id = request.form['task']
    assign_task(user_id, task_id)
    return redirect(find_redirect(request.form['type'], request.form['id']))

@view_blueprint.post('/unassign')
def post_unassign():
    user_id = request.form['user']
    task_id = request.form['task']
    unassign(user_id, task_id)
    return redirect(find_redirect(request.form['type'], request.form['id']))

@view_blueprint.post('/change_duedate')
def post_change_duedate():
    task_id = request.form['task']
    duedate = request.form['duedate']
    change_duedate(task_id, duedate)
    return redirect(find_redirect(request.form['type'], request.form['id']))

@view_blueprint.post('/delete_task')
def post_delete_task():
    task_id = request.form['task']
    delete_task(task_id)
    return redirect(find_redirect(request.form['type'], request.form['id']))

@view_blueprint.post('/edit_task')
def post_edit_task():
    task_id = request.form['task']
    content = request.form['content']
    change_content(task_id, content)
    return redirect(find_redirect(request.form['type'], request.form['id']))

@view_blueprint.get('/user/<int:user_id>')
def user_dashboard(user_id):
    users = User.query.all()
    tasks = Task.query.all()
    for task in tasks: 
        task.is_overdue()
    db.session.commit()
    projects = Project.query.all()
    user = User.query.filter_by(id=user_id).first()
    return render_template('user.html', user = user, users = users, task=tasks, projects=projects)

@view_blueprint.post('/user/<int:user_id>')
def post_user_dashboard(user_id):
    task_id = request.form['id']
    task = Task.query.filter_by(id=int(task_id)).first()
    task.complete = True 
    db.session.commit()
    return redirect(url_for('views.user_dashboard', user_id=user_id))

@view_blueprint.get('/project/<int:project_id>')
def project_dashboard(project_id):
    users = User.query.all()
    tasks = Task.query.all()
    notes = Note.query.all()
    for task in tasks: 
        task.is_overdue()
    db.session.commit()
    projects = Project.query.all()
    project = Project.query.filter_by(id=project_id).first()
    return render_template('project.html', project = project, users = users, task=tasks, projects=projects, len = len, notes = notes)

@view_blueprint.post('/project/<int:project_id>')
def post_project_dashboard(project_id):
    task_id = request.form['id']
    task = Task.query.filter_by(id=int(task_id)).first()
    task.complete = True 
    db.session.commit()
    return redirect(url_for('views.project_dashboard', project_id=project_id))

@view_blueprint.post('/create_project')
def post_create_project():
    project = request.form['name']
    create_project(project)
    return redirect(url_for('views.get_home'))

@view_blueprint.get('/create_project')
def get_create_project():
    users = User.query.all()
    tasks = Task.query.all()
    projects = Project.query.all()
    return render_template('create_project.html', users = users, tasks = tasks, projects = projects)

@view_blueprint.post('/delete_project')
def post_delete_project(): 
    project_id = request.form['id']
    delete_project(project_id)
    return redirect(url_for('views.get_home'))

@view_blueprint.post('/kill_project')
def post_kill_project(): 
    project_id = request.form['id']
    kill_project(project_id)
    return redirect(url_for('views.get_home'))

@view_blueprint.get('/colorpicker')
def get_colorpicker():
    return render_template('colorpicker.html')

@view_blueprint.post('/colorpicker')
def post_colorpicker():
    global color
    new_color = request.form['color']
    color = new_color
    return render_template('colorpicker.html')

@view_blueprint.post('/create_note')
def post_create_note():
    user_id = request.form['user']
    task_id = request.form['task']
    content = request.form['content']
    project = request.form['project']
    print(project)
    create_note(content, task_id, user_id)
    return redirect(url_for('views.project_dashboard', project_id=project))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="icon" type="image/png" href="{{url_for('static', filename = 'logo.png')}}" sizes="32x32">
        <title>{%block title%}{%endblock%} - Taskapp</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="{{url_for('static', filename = 'offcanvas.css')}}">
        <link rel="stylesheet" href="{{url_for('static', filename = 'utils.css')}}">
        <style>
            .btn {
                background-color: {{ color }} !important;
                border-color: {{ border }} !important;
            }
            .btn:hover,
            .btn:focus {
                background-color: {{ hover }} !important;
                border-color: {{ border }} !important;
            }
            .btn:active {
                background-color: {{ active_color }} !important;
                border-color: {{ active_border }} !important;
            }
        </style>
    </head>
    <body>
        <nav class="navbar" style="background: {{color}}" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                    <img  src="{{url_for('static', filename = 'logo.png')}}" width="50" height="50">
                </a>
            </div>
        </nav>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasExampleLabel">Menu</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <div style="margin-bottom: 1rem;">
                    <a class="btn btn-outline-primary w-100" href="{{url_for('views.get_create_user')}}">
                        <i class="bi bi-person-plus-fill"></i> Crear Usuario
                    </a>
                    <a class="btn btn-outline-primary w-100 mt-2" href="{{url_for('views.get_create_project')}}">
                        <i class="bi bi-folder-plus"></i> Crear Proyecto
                    </a>
                    <a class="btn btn-outline-primary w-100 mt-2" href="{{url_for('views.get_home')}}">
                        <i class="bi bi-house-door-fill"></i> Home
                    </a>
                </div>
                <div class="dropdown mb-3">
                    <button class="btn btn-primary dropdown-toggle w-100" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown">
                        <i class="bi bi-people-fill"></i> Usuarios
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    {%for user in users%}
                        <li><a class="dropdown-item" href="{{url_for('views.user_dashboard', user_id=user.id)}}">{{user.username}}</a></li>
                    {%endfor%}
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle w-100" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown">
                        <i class="bi bi-briefcase-fill"></i> Proyectos
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                    {%for project in projects%}
                        <li><a class="dropdown-item" href="{{url_for('views.project_dashboard', project_id=project.id)}}">{{project.name}}</a></li>
                    {%endfor%}
                    </ul>
                    <br />
                    <div class="offcanvas-footer">
                        <hr>
                        <div class="row">
                            <div class="col text-center">
                                <a href="https://ticio.co/" style="color:#6c757d"><i class="bi bi-box-arrow-up-right"></i></a>
                            </div>
                            <div class="col text-center">
                                <a href="https://www.linkedin.com/company/ticio" style="color:#6c757d"><i class="bi bi-linkedin"></i></a>
                            </div>
                            <div class="col text-center">
                                <a href="https://youtube.com/@ticio-uk4sl?si=6uoD4GPvTTjxyTvp" style="color:#6c757d"><i class="bi bi-youtube"></i></a>
                            </div>
                            <div class="col text-center">
                                <a href="https://github.com/TicioChatbot/taskapp" style="color:#6c757d"><i class="bi bi-github"></i></a>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col text-center">
                                <small>&copy; 2024 Taskapp by Ticio</small>
                            </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
        
          </div>
        <br>
        <div class="container-fluid px-3 px-md-5">
            <form class="row gx-5" method="post" action="{{url_for('views.post_create_task')}}">
                {%block origin%}{%endblock%}
                <div class="col-12 col-md-auto">
                    <input type="text" class="form-control" name="content" placeholder="Tarea">
                </div>
                <div class="col-12 col-md-auto">
                    <input type="date" class="form-control" name="duedate">
                </div>
                <div class="col-12 col-md-auto">
                    <select class="form-select"  style="width: 200px;" name="user">
                        <option selected>Usuario</option>
                        {%for user in users %}
                        <option value="{{user.id}}">{{user.username}}</option>
                        {%endfor%}
                    </select>
                </div>
                <div class="col-12 col-md-auto">
                    <select class="form-select" style="width: 200px;" name="project">
                        <option selected>Proyecto</option>
                        {%for project in projects%}
                        <option value="{{project.id}}">{{project.name}}</option>
                        {%endfor%}
                    </select>
                </div>
                <div class="col-12 col-md-auto">
                    <button type="submit" class="btn btn-primary">Crear Tarea</button>
                </div>
            </form>
        </div>
        </div>
        </div>
        <br />
        <div class="container">
        {%block content%}{%endblock%}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                var modals = document.querySelectorAll('.modal.fade');

                modals.forEach(function (modal) {
                    modal.addEventListener('show.bs.modal', function (event) {
                        // Button that triggered the modal
                        var button = event.relatedTarget;

                        // Extract info from data-* attribute
                        var field = button.getAttribute('data-field');

                        // Update the modal's hidden input fields
                        var inputFields = modal.querySelectorAll('.hiddenField');

                        inputFields.forEach(function (inputField) {
                            inputField.value = field;
                        });
                    });
                });
            });
        </script>
    </body>
</html>

app/templates/colorpicker.html
{% extends "base.html"%}
{%block title%}Personalizar{%endblock%}
{%block content%}
<form method="post" action="{{url_for('views.post_colorpicker')}}">
    <input type="color" name="color">
    <input type="submit"> 
</form>
{%endblock%}

app/templates/create_project.html
{% extends "base.html"%}
{%block title%}Crear Usuario{%endblock%}
{%block origin%}<input type="hidden" value="home" name="type"><input type="hidden" value="0" name="id">{%endblock%}
{%block content%}
<form action="{{url_for('views.post_create_project')}}" method="post">
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Nombre del proyecto</label>
      <input type="text" class="form-control" name="name">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{%endblock%}

app/templates/create_user.html
{% extends "base.html"%}
{%block title%}Crear Usuario{%endblock%}
{%block origin%}<input type="hidden" value="home" name="type"><input type="hidden" value="0" name="id">{%endblock%}
{%block content%}
<form action="{{url_for('views.post_create_user')}}" method="post">
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Nombre de Usuario</label>
      <input type="text" class="form-control" name="username">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{%endblock%}

app/templates/user.html
{% extends "base.html"%}
{%block title%}{{user.username}}{%endblock%}
{%block origin%}<input type="hidden" value="user" name="type"><input type="hidden" value="{{user.id}}" name="id">{%endblock%}
{%block content%}
<div class="container-fluid">
    <div class="d-flex align-items-center">
        <h1>{{user.username}}</h1>
        <button class="complete-tasks-button ms-3" type="button" data-bs-toggle="collapse" data-bs-target="#demoCollapse" aria-expanded="false" aria-controls="demoCollapse">
            <i class="bi bi-person-check"></i>
        </button>
    </div>
    <div class="container">
        <br/>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Tarea</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Proyecto</th>
                    <th scope="col">Status</th>
                    <th scope="col">Comentarios</th>  <!-- Added column for Comentarios -->
                    <th scope="col"></th>  <!-- Extra column for options/actions -->
                </tr>
            </thead>
            <tbody>
                {% for task in user.backref %}
                {% if not task.complete %}
                <tr>
                    <td>{{ task.content }}</td>
                    <td>{{ task.duedate }}</td>
                    <td>{{ task.project }}</td>
                    <td>
                        {% if task.overdue %}
                            <i class="bi bi-patch-minus-fill" style="color: red"></i>
                        {% else %}
                            <i class="bi bi-patch-exclamation-fill" style="color: rgb(212, 212, 0)"></i>
                        {% endif %}
                    </td>
                    <td>
                        <a class = "option-buttons" href="#" data-bs-toggle="modal" data-bs-target="{{task.task_hashtag()}}"><i class="bi bi-card-text"></i></a>   
                    </td>
                    <td>
                        <div class="btn-group dropend">
                            <button class="option-buttons" type="button" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#cambiarfecha" data-field="{{ task.id }}">Cambiar Fecha</a></li>
                                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#asignar" data-field="{{ task.id }}">Asignar</a></li>
                                <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#editar" data-field="{{ task.id }}">Editar</a></li>
                                <li>
                                    <form method="post" action="{{ url_for('views.post_delete_task') }}">
                                        <input type="hidden" value="{{ task.id }}" name="task">
                                        <input type="hidden" value="{{ task.project }}" name="id">
                                        <button type="submit" class="dropdown-item">Eliminar</button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        <div class="collapse" id="demoCollapse">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Tarea</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Proyecto</th>
                        <th scope="col">Status</th>
                        <th scope="col">Comentarios</th>  <!-- Added column for Comentarios -->
                        <th scope="col"></th>  <!-- Extra column for options/actions -->
                    </tr>
                </thead>
                <tbody>
                    {% for task in user.backref %}
                    {% if task.complete %}
                    <tr>
                        <td>{{ task.content }}</td>
                        <td>{{ task.duedate }}</td>
                        <td>{{ task.project }}</td>
                        <td><i class="bi bi-patch-check-fill" style="color: green;"></i></td>
                        <td>
                            <a class = "option-buttons" href="#" data-bs-toggle="modal" data-bs-target="{{task.task_hashtag()}}"><i class="bi bi-card-text"></i></a>   
                        </td>
                        <td>
                            <div class="btn-group dropend">
                                <button class="option-buttons" type="button" data-bs-toggle="dropdown"><i class="bi bi-three-dots-vertical"></i></button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#cambiarfecha" data-field="{{ task.id }}">Cambiar Fecha</a></li>
                                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#asignar" data-field="{{ task.id }}">Asignar</a></li>
                                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#editar" data-field="{{ task.id }}">Editar</a></li>
                                    <li>
                                        <form method="post" action="{{ url_for('views.post_delete_task') }}">
                                            <input type="hidden" value="{{ task.id }}" name="task">
                                            <input type="hidden" value="{{ task.project }}" name="id">
                                            <button type="submit" class="dropdown-item">Eliminar</button>
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    <div class="modal fade" id="cambiarfecha" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Cambiar Fecha</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{{url_for('views.post_change_duedate')}}">
                        <input type="hidden" class="hiddenField" name="task">
                        <input type="date" class="form-control" name="duedate">
                        <input type="hidden" value="{{user.id}}" name="id">
                        <input type="hidden" value="user" name="type">
                        <br>
                        <button type="submit" class="btn btn-primary">Cambiar Fecha</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="asignar" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Asignar</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex flex-column justify-content-center align-items-center">
                    <form method="post" action="{{url_for('views.post_assign_task')}}">
                        <input type="hidden" class="hiddenField" name="task">
                        <input type="hidden" value="{{user.id}}" name="id">
                        <input type="hidden" value="user" name="type">
                        <select class="form-select"  style="width: 200px;" name="user">
                            <option selected>Usuario</option>
                            {%for user in users %}
                            <option value="{{user.id}}">{{user.username}}</option>
                            {%endfor%}
                        </select>
                        <br>
                        <button type="submit" class="btn btn-primary">Asignar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="editar" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body d-flex flex-column justify-content-center align-items-center">
                    <form method="post" action="{{url_for('views.post_edit_task')}}">
                        <input type="hidden" class="hiddenField" name="task">
                        <input type="hidden" value="{{user.id}}" name="id">
                        <input type="hidden" value="proyect" name="type">
                        <input type="text" placeholder="Tarea" class="form-control" name="content">
                        <br>
                        <button type="submit" class="btn btn-primary">Editar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {%for task in user.backref%}
    <div class="modal fade" id="{{task.task_finder()}}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Comentarios</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Display existing comments -->
                {% for note in task.notes %}
                <div class="mb-2">
                    <h6 class="mb-1">{{ note.author }}</h6>
                    <p>{{ note.content }}</p>
                </div>
                {% endfor %}
            </div>
            <div class="modal-footer">
                <!-- Add new comment form -->
                <form class="row g-3" method="post" action="{{ url_for('views.post_create_note') }}">
                    <div class="col-12 col-md-6">
                        <select class="form-select" name="user">
                            <option selected>Autor</option>
                            {% for user in users %}
                            <option value="{{ user.id }}">{{ user.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-12 col-md-6">
                        <input type="text" class="form-control" name="content" placeholder="Añadir comentario">
                    </div>
                    <!-- Hidden fields -->
                    <input type="hidden" name="task" value="{{ task.id }}">
                    <input type="hidden" name="project" value="{{ task.project.id }}">
                    <!-- Submit button -->
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary w-100">Comentar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endfor %}
</div>
{%endblock%}